inventory:
    plugin: SimpleInventory
    options:
        host_file: "static/nornir/hosts.yaml"
        group_file: "static/nornir/groups.yaml"
runner:
    plugin: threaded
    options:
        num_workers: 10