DC-R1:
  data:
    location: Poznań Beyond.pl Datacenter 2
  groups:
  - DC-ROUTER
  hostname: 192.168.1.2
ISP-R1:
  data:
    location: Poznań Beyond.pl Stary browar
  groups:
  - DC-ROUTER
  hostname: 13.0.0.2
SB-R-1000:
  data:
    location: "Gdańsk Altanki"
    number: 1000
    subnet: 172.16.0.0/24
  groups:
  - SB-ROUTER
  hostname: 172.16.0.255
SB-R-1001:
  data:
    location: "Wrocław Opatowicka"
    number: 1001
    subnet: 172.16.1.0/24
  groups:
  - SB-ROUTER
  hostname: 172.16.1.255
SB-R-1002:
  data:
    location: "Toruń Polna"
    number: 1002
    subnet: 172.16.2.0/24
  groups:
  - SB-ROUTER
  hostname: 172.16.2.255
