DC-R1:
  data:
    location: DataCenter
  groups:
  - DC-ROUTER
  hostname: 192.168.1.2
ISP-R1:
  data:
    location: ISP
  groups:
  - DC-ROUTER
  hostname: 13.0.0.2
SB-R-1000:
  data:
    location: "Gda\u0144sk"
    number: 1000
    subnet: 172.16.0.0/24
  groups:
  - SB-ROUTER
  hostname: 172.16.0.255
SB-R-1001:
  data:
    location: "Wroc\u0142aw"
    number: 1001
    subnet: 172.16.1.0/24
  groups:
  - SB-ROUTER
  hostname: 172.16.1.255
SB-R-1002:
  data:
    location: "Toru\u0144"
    number: 1002
    subnet: 172.16.2.0/24
  groups:
  - SB-ROUTER
  hostname: 172.16.2.255
SB-R-1003:
  data:
    location: "\u021Aig\u0103ne\u0219ti"
    number: 1003
    subnet: 172.16.3.0/24
  groups:
  - SB-ROUTER
  hostname: 172.16.3.255
